aws_region         = "eu-north-1"
project_name       = "Terraform VPC Lab"
environment        = "Lab"
vpc_cidr           = "10.0.0.0/16"
public_subnet_cidr = "10.0.1.0/24"
availability_zone  = "eu-north-1a"